### ISSUE TITLE
just question: can any one tell me the effect for the configuration forwarding_timeouts

### ISSUE THREAD

**Issue by darmenliu** [hellofresh/janus#439]
[Short description of problem here]
I found that janus have below configuration, but I can't found any description from janus guide, can any one tell me what's the effect for such configuration, what's the different between dial_timeout and response_header_timeout.

       "forwarding_timeouts" : {
            "dial_timeout" : "5s",
            "response_header_timeout" : "17s"
        },

**Comment by vgarvardt** [comment]
- `dial_timeout` is the dialer timeout, so this is the timeout for establishing a connection to an upstream
- `response_header_timeout` is the waiting for response headers timeout after the request was sent. This parameter is used to set `http.Transport.ResponseHeaderTimeout` field, so maybe description for the field in https://golang.org/pkg/net/http/#Transport will make it slightly more clear for you

**Comment by darmenliu** [comment]
@vgarvardt thanks a lot.
